In [ ]:
#a.Импортировать библиотеку Numpy
import numpy as np

In [ ]:
#b.Создать массив из 10 нулей
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#c.Создать массив из 10 единиц
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#d.Создать массив из 10 пятёрок
a=np.ones(10)*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#e.Создать массив из целых чисел от 10 до 50
a=np.arange(10,51)
print(a)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#f.Создать массив из четных чисел от 10 до 50
a=np.arange(10,51,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#g.Создать матрицу 3х3 с числами от 0 до 8
m=np.arange(0,9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#h.Создать единичную матрицу 3х3
m=np.eye(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#i.Использовать NumPy для генерации случайного числа от 0 до 1
r=np.random.rand()
print(r)

0.22378354167980363


In [ ]:
#j.Использовать NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения
r=np.random.rand(25)
print(r)

[0.66975636 0.06150597 0.94187539 0.60210368 0.23497453 0.45222621
 0.88779274 0.03634055 0.69795932 0.50787797 0.05840529 0.70510366
 0.52005111 0.19921223 0.84623415 0.90712935 0.67034425 0.49707443
 0.03067527 0.92751692 0.79903587 0.27649799 0.61747641 0.37700528
 0.11338637]


In [ ]:
#k.Создать следующую матрицу, используя функции библиотеки NumPy
m=np.arange(0.01, 1.01, 0.01).reshape(10,10)
print(m)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
#l.Дана стартовая матрица.
mat=np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#задание l.
print(mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
#задание m.
print(mat[mat==20])

[20]


In [ ]:
#задание n.
print(mat[0:3,1].reshape(3,1))

[[ 2]
 [ 7]
 [12]]


In [ ]:
#задание o.
print(mat[4:])

[[21 22 23 24 25]]


In [ ]:
#задание p.
print(mat[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#q.Получить сумму всех значений в стартовой матрице mat
print(mat.sum())

325


In [ ]:
#r.Получить стандартное отклонение в стартовой матрице mat
print(mat.std())

7.211102550927978


In [ ]:
#s.Получить сумму значений в колонках в стартовой матрице mat
print(mat.sum(axis=0))

[55 60 65 70 75]
